name: crust
description: Toast would not be toast without the crust
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

    # Flutter
    flutter:
        sdk: flutter

    # Redux
    flutter_redux: ^0.5.2
    redux: ^3.0.0
    redux_logging: ^0.3.0
    redux_persist_flutter: ^0.8.0-rc.0
    redux_persist: ^0.8.0-rc.0
    redux_thunk: ^0.2.0

    # Auth
    flutter_facebook_login: ^1.1.1
    google_sign_in: ^3.2.4

    # Utils
    cupertino_icons: ^0.1.2
    flutter_statusbarcolor: 0.2.0
    flutter_svg: ^0.6.3
    graphql_flutter: ^0.9.5
    http: ^0.12.0
    intl: ^0.15.7
    multi_image_picker: ^3.0.22
    qr_flutter: ^2.0.0+51
    timeago: ^2.0.9
    tuple: ^1.0.2
    flutter_image_compress: ^0.2.4
    cached_network_image: ^0.5.0
    shimmer: ^1.0.0

    # Firebase
    firebase_core: ^0.3.1+1
    firebase_storage: ^2.1.0+1
    firebase_auth: ^0.8.1+4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: "^0.7.0"


dependency_overrides:
  http: ^0.12.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    assets:
      - assets/images/
      - assets/svgs/

    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.io/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.io/assets-and-images/#from-packages

    fonts:
    -   family: CrustCons
        fonts:
        -   asset: assets/fonts/CrustCons.ttf

    -   family: GrandHotel
        fonts:
        -   asset: assets/fonts/GrandHotel-Regular.ttf

    -   family: OpenSans
        fonts:
        -   asset: assets/fonts/OpenSans-Light.ttf
        -   asset: assets/fonts/OpenSans-Regular.ttf
        -   asset: assets/fonts/OpenSans-Bold.ttf
        -   asset: assets/fonts/OpenSans-ExtraBold.ttf

    -   family: PTSans
        fonts:
        -   asset: assets/fonts/PTSans-Regular.ttf
        -   asset: assets/fonts/PTSans-Bold.ttf


flutter_icons:
    ios: true
    android: true
    image_path_ios: "assets/launcher/icon.png"
    image_path_android: "assets/launcher/icon.png"
    adaptive_icon_background: "assets/launcher/background.png"
    adaptive_icon_foreground: "assets/launcher/foreground.png"
